- src: https://unpkg.com/@shgysk8zer0/polyfills@0.6.2/browser.min.js
  crossOrigin: anonymous
  referrerPolicy: no-referrer
  integrity: sha384-7yz8QDqFdoZyAnsrpHCA/lGoTyWgsFBb4jWnbCDDEDI/AUhhqgBPDhAejhhSRgAN
  defer: true
- src: /js/index.min.js
  referrerPolicy: no-referrer
  defer: true
- src: /js/components.min.js
  referrerPolicy: no-referrer
  defer: true
