name: Jekyll Template
shortName: Jekyll Template
version: 1.0.14-a1
lang: en
dir: ltr
display: standalone
orientation: any
description: "A GitHub repository for easily creating fast, modern, PWA compatible websites"
icons-file: /img/icons.svg
theme:
  color: '#528ff9'
  background: '#242424'
icons:
- src: /img/favicon.svg
  type: image/svg+xml
  sizes: 150x150
  purpose: maskable any
- src: /img/apple-touch-icon.png
  rel: apple-touch-icon
  type: image/png
  sizes: 180x180
- src: /img/icon-512.png
  type: image/png
  sizes: 512x512
  purpose: maskable any
- src: /img/icon-192.png
  type: image/png
  sizes: 192x192
  purpose: maskable any
- src: /img/icon-32.png
  type: image/png
  sizes: 32x32
- src: /img/icon-16.png
  type: image/png
  sizes: 16x16
screenshots:
- src: 'https://i.imgur.com/uRKaQQQh.png'
  sizes: 1024x567
  type: image/png
- src: 'https://i.imgur.com/uRKaQQQl.png'
  sizes: 640x354
  type: image/png
- src: 'https://i.imgur.com/uRKaQQQm.png'
  sizes: 320x127
  type: image/png
- src: 'https://i.imgur.com/uRKaQQQt.png'
  sizes: 160x89
  type: image/png
# https://web.dev/app-shortcuts/
shortcuts:
- name: Bacon Ipsum
  description: Test article and shortcut
  url: /posts/2019/10/29/test/
  icons:
  - src: /img/post.svg
    sizes: 192x192
    type: image/svg+xml
  - src: /img/post-192.png
    sizes: 192x192
    type: image/png
  - src: /img/post-144.png
    sizes: 144x144
    type: image/png
  - src: /img/post-96.png
    sizes: 96x96
    type: image/png
  - src: /img/post-72.png
    sizes: 72x72
    type: image/png
  - src: /img/post-48.png
    sizes: 48x48
    type: image/png
  - src: /img/post-36.png
    sizes: 36x36
    type: image/png
related_applications: []
features: []
categories: []
